/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/vladimirkopylov/bots/bots/FDT_BOT_RF/fdt_bot.py': [Errno 2] No such file or directory
